import NavItem from "../components/NavItem";
import { Image, LayoutContainer } from "../layouts/LayoutContainer";
const image: Image = {
  id: "image",
  alt: "background image",
  url: "https://media.istockphoto.com/id/1346944001/photo/close-up-of-co-workers-stacking-their-hands-together.jpg?s=2048x2048&w=is&k=20&c=nB37AAthL5AINPEz4tK8kiYHGjJm_YtKuSjJZvOiqfA=",
};

export function HomeAboutPeerData() {
  return (
    <LayoutContainer title="About PEER DATA" image={image}>
      <p className="text-md mt-6 leading-snug text-brand-500">
        PEER DATA is borne out of the observation that data and AI are powering
        nearly everything we do today. Data, as the vital commodity powering the
        AI and digital world, holds immense value and potential.
      </p>
      <p className="text-md relative mt-4 leading-snug text-brand-500">
        With decades of experience in the field, our team has witnessed the
        transformative journey of data, from its role in supporting human
        decision-making to empowering machines to make informed choices in
        financial markets and everyday life on a global scale. We have
        recognized the importance of data as foundational building blocks in
        facilitating the introduction of new asset classes, ensuring their
        operational scalability and fostering transparency among all
        stakeholders involved.
      </p>
      <p className="text-md relative mt-4 leading-snug text-brand-500">
        Data is experiencing exponential growth, having doubled in just the past
        two years. Yet, despite the ever-increasing demand for diverse and
        extensive datasets, there is currently no direct avenue for investing in
        data. The data discovery process remains predominantly manual, and
        evaluating data quality is a time-consuming and subjective endeavor.
        While we often humorously remark that "
        <span className="font-bold text-black italic">
          everyone is in the data business, they just don't know it yet,
        </span>
        " the reality is that there is a lack of clear means to capitalize on
        the financial opportunities generated by one's own data.
      </p>
      <div className="relative mt-4">
        <p className="text-md leading-snug text-brand-500">
          To address this challenge, PEER DATA has embarked on a mission to
          assist organizations in transforming their data into valuable assets.
          We aim to unlock maximum value and amplify reach by:
        </p>
        <ul className="text-md relative ml-4 mt-4 list-outside list-disc leading-snug text-brand-500">
          <li>
            Providing expertise, standard, and cutting-edge technology to build
            infrastructure and rails for the data asset class
          </li>
          <li>Enabling digital discovery and monetization of data</li>
          <li>
            Connecting data owners, investors, and consumers to trade data as an
            asset
          </li>
        </ul>
      </div>
      <div className="mt-10 flex items-center gap-x-6">
        <NavItem
          id="about"
          to="/about"
          className="rounded-md bg-brand-blue px-8 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-brand-blue/80 hover:shadow-[0_2px_15px_-3px_rgba(0,0,0,0.07),0_10px_20px_-2px_rgba(0,0,0,0.04)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-blue"
        >
          About Us
        </NavItem>
      </div>
    </LayoutContainer>
  );
}

export default HomeAboutPeerData;
