import { Hero } from "../../containers/Hero";
// import CategoryContainer from "../../containers/CategoryContainer";
import HomeAboutPeerData from "../../containers/HomeAboutPeerData";
import JoinContainer from "../../containers/JoinContainer";
import { SplitImages } from "../../containers/SplitImages";
import { LeftText } from "../../containers/LeftText";
import { DataEconomyRoles } from "../../containers/DataEconomyRoles";
import Home1 from "../../assets/images/image-home-1.jpg";
import Home2 from "../../assets/images/image-home-2.jpg";
import Home3 from "../../assets/images/image-home-3.jpg";
import Home4 from "../../assets/images/image-home-4.jpg";
import { Button } from "../../components/Button";
import { ValueProps } from "../../containers/ValueProps";
import Signup from "../../containers/SignUp";
import AlternateHero from "../../containers/AlternateHero";
import competitiveEdges from "../../payload/competitve_edges.json";
import { CompanyHistory } from "../../containers/CompanyHistory";
import { CompanyTransparency } from "../../containers/CompanyTransparency";
import { JoinOurTeam } from "../../containers/JoinOurTeam";

// const Images = {
//   "home-1": "../../assets/images/image-home-1.jpg",
// };

export interface Company {
  className?: string;
}
export function Company({ className }: Company) {
  return (
    <section className={className}>
      <AlternateHero className="px-12" />
      <CompanyHistory
        className="min-h-screen px-12"
        category="History"
        mainContent='The data discovery process remains predominantly manual, and evaluating data quality is a time-consuming and subjective endeavor. While we often humorously remark that "everyone is in the data business, they just dont know it yet," the reality is that therer is as lack of clear means to capitalize on the financial opportunities generated by one&apos;s own data.'
      />
      <CompanyTransparency
        className="min-h-screen px-12"
        category="Fostering Transparency"
        mainContent="We have recognized the importance of data as foundational building blocks in facilitating the introduction of new asset classes, ensuring their operational stability and fostering transparency among all stakeholders involved."
      />

      <hr className="mb-52 mt-28 h-0.5 bg-brand-dark-blue px-12 lg:mx-12" />
      <ValueProps
        items={competitiveEdges.data as ValueProps["items"]}
        className="px-12"
        buttonLabel="Find out more"
        title="PEER DATA is helping the participants in the data ecosystem by building tools which:"
        onClick={() => console.log("click")}
      />
      <JoinOurTeam
        className="px-12"
        title="Join our team"
        mainContent="Are you someone who loves collobration while having a thirst for knowledge when it comes to data science? Then head over to our job listings today!"
      />
      <SplitImages className="mt-20 h-3/4 px-12" left={Home3} right={Home4} />
    </section>
  );
}
